version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_ENV: "prod"
        S3_BUCKET : "cicdoutputartifact"
        BUILD_FOLDER : "target"
phases:
    install:
        runtime-versions:
            java: openjdk8
        commands:
            - echo Installing source mvn dependencies...
            - apt-get update
            - apt -y install default-jre
            - apt install maven
            
           
    build:
        commands:
            - echo Build started on `date`
            - mvn clean install 
    post_build:
     commands:
      - echo Build completed on `date`
       -aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive
artifacts: 
  base-directory: target*
  files: 
    - "*/*"
    - 'appspec.yml'
    - 'scripts'
