files:
  - source: /
    destination: /opt/wildfly/wildfly-16.0.0.Final/wildfly-16.0.0.Final/standalone/deployments
hooks:


  ApplicationStart:
    - location: app_start.sh
      timeout: 300
      runas: ubuntu
